project:
  type: website
  output-dir: docs

website:
  title: "Zhengyang (John) Fei"
  site-url: "johnyzyfei.github.io/zhengyang-fei/"
  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "Zhengyang Fei, University of Toronto @ 2025"
  navbar:
    right:
      - href: index.qmd
        text: About
      - text: "CV"
        href: resume.qmd
      - href: project.qmd
        text: Projects
      - href: blog.qmd
        text: Blog
      - href: teaching.qmd
        text: Teaching
      - icon: github
        href: https://github.com/johnyzyfei/
      - icon: linkedin
        href: https://www.linkedin.com/in/zhengyang-fei

format:
  html:
    theme: Zephyr
    css: styles.css
    toc: true

editor: visual

execute:
  freeze: auto

engine: knitr
        
